// packages/core/vue/solutions/[...all].vue
<template>
  <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-white to-gray-50 dark:from-neutral-950 dark:to-neutral-900 px-6">
    <div className="text-center">
      <p className="text-8xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 select-none">
        404
      </p>
      <h1 className="mt-4 text-2xl font-semibold text-gray-800 dark:text-gray-200">
        ? ? ? ?
      </h1>
      <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
        你还没做这个题
      </p>
    </div>
  </main>
</template>

// packages/core/react/solutions/[...all].tsx
function NotFound() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-white to-gray-50 dark:from-neutral-950 dark:to-neutral-900 px-6">
      <div className="text-center">
        <p className="text-8xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 select-none">404</p>
        <h1 className="mt-4 text-2xl font-semibold text-gray-800 dark:text-gray-200">? ? ? ?</h1>
        <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">你还没做这个题</p>
      </div>
    </main>
  )
}

export default NotFound
