// packages/core/vue/problems/01/index.vue
<script setup lang="ts">
import { ProblemAnswer, ProblemDescription, Problems } from '../../layout'
import Button from './Button.vue'
import Description from './README.md'
</script>

<template>
  <Problems>
    <ProblemDescription>
      <Description />
    </ProblemDescription>
    <ProblemAnswer>
      <Button />
    </ProblemAnswer>
  </Problems>
</template>

// packages/core/seam/react/problems/01/index.tsx
import { ProblemAnswer, ProblemDescription, Problems } from '../../layout'
import Answer from './answer.mdx'
import Description from './README.mdx'

export default function Problem() {
  return (
    <Problems>
      <ProblemDescription>
        <Description />
      </ProblemDescription>
      <ProblemAnswer>
        <Answer />
      </ProblemAnswer>
    </Problems>
  )
}
