// packages/core/react/solutions/gcy/01/index.tsx
import { ProblemAnswer, ProblemDescription, Problems } from '@layout/index'
import Button from './Button'
import Description from './README.mdx'

export default function Problem() { // default | outline | text
  return (
    <Problems>
      <ProblemDescription>
        <Description />
      </ProblemDescription>
      <ProblemAnswer>
        {/* Your answer goes here */}
        <Button variant="default" loading={true}> Click Me</Button>
      </ProblemAnswer>
    </Problems>
  )
}

// packages/core/vue/solutions/seam/01/index.vue
<script setup lang="ts">
import { ProblemAnswer, ProblemDescription, Problems } from '@layout/index'
import Button from './Button.vue'
import Description from './README.md'
</script>

<template>
  <Problems>
    <ProblemDescription>
      <Description />
    </ProblemDescription>
    <ProblemAnswer>
      <Button variant="destructive">
        click me
      </Button>
    </ProblemAnswer>
  </Problems>
</template>
